# Week-1 Assignment

**Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.**

P.S. You might find use of functions which you have never used before.So feel free to google

# Section0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [22]:
#your code here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Section1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

In [102]:
def isValid(A,B):
    if len(A[0])==len(B):
      return True
    else:
        return False

##### (i) Check if matrix multiplication is valid

In [23]:
def isValid(A,B):
    if len(A[0])==len(B):
      return True
    else:
        return False

##### (ii) Using loops (without using numpy)

In [24]:
def matrix_multiply(A,B):
  #your code here
    C = [[0 for _ in range(len(B[0]))]for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
          for k in range(len(A[0])):
            C[i][j] = C[i][j] + A[i][k] * B[k][j]
    return C

##### (iii) Using numpy

In [25]:
def matrix_multiply_2(A,B):
  #your code here
  def matrix_multiply_2(A,B):
    A = np.array(A)
    B = np.array(B)
    matrix_multiply = np.dot(A, B)
    return matrix_multiply

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102, 108, 114], [246, 261, 276], [390, 414, 438], [534, 567, 600]]
Result using numpy: None


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [87]:
def mean(x):

  mean =sum(x)/len(x)
  return mean

In [88]:
def standard_deviation(x):


    std_dev =(sum((x-mean)**2 for x in x)/len(x))**0.5
    return std_dev

In [89]:
def zscore_normalisation(x):
  #your code here
  normalized_data=[(x-mean)/std_dev for i in x]
  return normalized_data

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [90]:
def zscore_normalisation_2(x):
  #your code here
  x_np = np.array(x)
  mean =  np.mean(x_np)
  std_dev = np.std(x_np)
  normalized_data = (x_np-mean)/std_dev
  return normalized_data

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [92]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]


print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.31068237,  0.91803138,  1.22170588,  1.89913361]), array([-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451,
       -0.06307086,  0.

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [97]:
def sigmoidfn(x):
  #your code here
    array_x = np.array(x)
    sigmoid = 1/(1 + np.exp(-x))
    return sigmoid

##### (ii) Write a fn to implement derivative of sigmoid fn

In [98]:
def derivative(x):
  #your code here
    derivative_sigmoid_x = sigmoidfn(x)* (-1 + sigmoidfn(x))
    return derivative_sigmoid_x

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [99]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01]]


# Section 2: Playing with Pandas

###Read the csv file


FileNotFoundError: ignored

###Display the shape of data frame


In [100]:
#your code here
data.shape
data.dtypes

NameError: ignored

###Return an array containing names of all the columns

In [ ]:
#your code here

###Display the number of null values in each column of the dataframe``



In [ ]:
#your code here

###Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
df['Property at Pressure']=df['Property'] + " at " + df['Pressure'].astype(str)
idx1=df[df['Property at Pressure']=='V at 10.0'].index
df['75'].loc[idx1].item()

16030.0

###Find out the column with the highest number of missing values

In [ ]:
#your code here

###What is the average enthalpy of Sat. Liq. at all different pressures in the dataset ?

In [ ]:
print(df['Liq_Sat'].iloc[2::4].mean())

936.9707720588235


###Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here

#Section 3: PLotting the PLOTS

###Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
#your code here

###Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
#your code here

#Linear Regression
You're given a 100 data points generated from the function
$y=mx+c$. Some noise is added to the y values.

**Task:** Estimate the values of m and c using linear regression. Write a suitable cost function and update the parameters.

In [ ]:
 # Generation of data points
x = np.random.rand(100)*100
y = -4*x+15
y = y+np.random.randn(100)*30
plt.scatter(x,y)

In [ ]:
# Initialisng parameters m and c such that the best fit line is given by y = m*x+c

#Cost function to be minimised

#Function for updating parameter


Run the model

In [ ]:
# define number of iterations for minimising cost function

# define the learning rate #

# run the model

In [ ]:
print(m,c)  # value should be close to (-4,15)