# Week-1 Assignment

**Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.**

P.S. You might find use of functions which you have never used before.So feel free to google

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Section0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [2]:
#your code here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

# Section1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  len(A[0]) != len(B)


9##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
     rows_A, cols_A = len(A), len(A[0])
     rows_B, cols_B = len(B), len(B[0])
     c =[[0 for _ in range(cols_B)] for _ in range(rows_A)]
     for i in range(rows_A):
         for j in range(cols_B):
             for k in range(cols_A):
                   C[i][j] += A[i][k] * B[k][j]
     return c

##### (iii) Using numpy

In [ ]:
def matrix_multiply_2(A,B):
  np.multiply(A,B)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Matrix multiplication is not valid


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
    global m= sum(x)/len(x)


SyntaxError: ignored

In [ ]:

def standard_deviation(x):
    var=sum(pow(i-m,2)for i in x)/len(x)
    globalstd=math.sqrt(var)



In [ ]:
def zscore_normalisation1(x):
    z= (x-m)/std


##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
  m=np.mean(x)
  s=np.std(x)
  z= (x-m)/s


##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation1(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

TypeError: ignored

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
   s=1/(1+math.exp^(-x))

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
  np.gradient(s,x)

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Playing with Pandas

###Read the csv file


In [3]:
df = pd.read_csv("superheated_vapor_properties.csv")
df

FileNotFoundError: ignored

###Display the shape of data frame


In [ ]:
pd.df.shape

AttributeError: ignored

###Return an array containing names of all the columns

###Display the number of null values in each column of the dataframe``



In [ ]:
#your code here

###Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
df['Property at Pressure']=df['Property'] + " at " + df['Pressure'].astype(str)
idx1=df[df['Property at Pressure']=='V at 10.0'].index
df['75'].loc[idx1].item()

16030.0

###Find out the column with the highest number of missing values

In [ ]:
#your code here

###What is the average enthalpy of Sat. Liq. at all different pressures in the dataset ?

In [ ]:
print(df['Liq_Sat'].iloc[2::4].mean())

936.9707720588235


###Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here

#Section 3: PLotting the PLOTS

###Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
#your code here

###Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
#your code here

#Linear Regression
You're given a 100 data points generated from the function
$y=mx+c$. Some noise is added to the y values.

**Task:** Estimate the values of m and c using linear regression. Write a suitable cost function and update the parameters.

In [ ]:
 # Generation of data points
x = np.random.rand(100)*100
y = -4*x+15
y = y+np.random.randn(100)*30
plt.scatter(x,y)

In [ ]:
# Initialisng parameters m and c such that the best fit line is given by y = m*x+c

#Cost function to be minimised

#Function for updating parameter


Run the model

In [ ]:
# define number of iterations for minimising cost function

# define the learning rate #

# run the model

In [ ]:
print(m,c)  # value should be close to (-4,15)