# Week-1 Assignment

**Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.**

P.S. You might find use of functions which you have never used before.So feel free to google

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Section0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
#your code here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Section1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  #your code here
  return len(A[0]) == len(B)
  if isValid(A,B):
    print ('Matrix multiplication is valid!')
  else
    print ('Matrix multiplication is not valid!')

##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
  #your code here
  return len(A[0]) == len(B)
  if matrix_multiply(A,B):
    result = [[0] * len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    print("Result:")
    for row in result:
        print(row)


##### (iii) Using numpy

In [ ]:
def matrix_multiply_2(A,B):
  #your code here
  import numpy as np
  # Supposing that matrix multiplication is already valid.
  result = np.dot(A, B)
    print("Result:")
    print(result)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

#Using loops
def matrix_multiply(A,B):

  return len(A[0]) == len(B)

A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

B = [
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
]

if matrix_multiply(A,B):
    result = [[0] * len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    print("Result:")
    for row in result:
        print(row)

#Using numpy
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

# Check if matrix multiplication is valid
if A.shape[1] == B.shape[0]:
    result = np.dot(A, B)
    print("Result:")
    print(result)



### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
  #your code here

  #for a particular dataset "x"
  mean(x) = sum(x) / len(x)

In [ ]:
def standard_deviation(x):
  #your code here

  #for a particular dataset "x"
  standard_deviation(x) = (sum((y - mean(x)) ** 2 for y in x) / len(x)) ** 0.5


In [ ]:
def zscore_normalisation(x):
  #your code here

  zscore_normalisation(x) = [(y - mean(x)) / standard_deviation(x) for y in x]

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
  #your code here

  import numpy as np
  # Calculate mean and standard deviation
  mean = np.mean(x)
  standard_deviation = np.std(x)

  # Z-score normalisation
  zscore_normalisation_2(x) = (x - mean) / standard_deviation

  print("Original data:", x)
  print("zscore_normalisation_2:", zscore_normalisation_2(x))

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

#Without using numpy
# Sample data
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]

# Calculate mean and standard deviation
mean = sum(x) / len(x)
standard_deviation = (sum((y - mean) ** 2 for y in x) / len(x)) ** 0.5

# Z-score normalization
zscore_normalisation = [(y - mean) / standard_deviation for y in x]

print("x:", x)
print("zscore_normalisation:", zscore_normalisation)

# Using numpy
import numpy as np

x = np.array([4, 7, 7, 15, 32, 47, 63, 89, 102, 131])
# Calculate mean and standard deviation
mean = np.mean(x)
standard_deviation = np.std(x)

# Z-score normalisation
zscore_normalisation_2(x) = (x - mean) / standard_deviation

print("x:", x)
print("zscore_normalisation_2:", zscore_normalisation_2(x))



### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
#Assuming input value to be a single data but not an array, we have to import math library!
import math
def sigmoidfn(x):
  #your code here
  return 1 / (1 + math.exp(-x))

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
  #your code here
  return sigmoidfn(x) * (1 - sigmoidfn(x))

  #Alternative method
  import math
  def derivative(x):
  return math.exp(x)/((1 + math.exp(x)) ** 2)

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

#For sigmoidfn(x)
import numpy as np

def sigmoidfn(x):
    return 1 / (1 + np.exp(-x))

x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
result = sigmoidfn(x)

print("Input array:", x)
print("x on applying sigmoid activation fn is:", result)


#For derivative(x) i.e. derivative of sigmoid function (x)
import numpy as np

def sigmoidfn(x):
    return 1 / (1 + np.exp(-x))

def derivative(x):
    return sigmoidfn(x) * (1 - sigmoidfn(x))

x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
result = derivative(x)

print("Input array:", x)
print("x on applying derivative of sigmoid activation fn is:", result)

# Section 2: Playing with Pandas

###Read the csv file


In [ ]:
df = pd.read_csv("superheated_vapor_properties.csv")


Pressure Property    Liq_Sat      Vap_Sat           75          100  \
0         1.0        V     1.0000  129200.0000  160640.0000  172180.0000   
1         1.0        U    29.3340    2385.2000    2480.8000    2516.4000   
2         1.0        H    29.3350    2514.4000    2641.5000    2688.6000   
3         1.0        S     0.1060       8.9767       9.3828       9.5136   
4        10.0        V     1.0100   14670.0000   16030.0000   17190.0000   
..        ...      ...        ...          ...          ...          ...   
539   11200.0        S     3.4440       5.5476          NaN          NaN   
540   11400.0        V     1.5040      15.2840          NaN          NaN   
541   11400.0        U  1450.0000    2527.2000          NaN          NaN   
542   11400.0        H  1467.2000    2701.5000          NaN          NaN   
543   11400.0        S     3.4575       5.5357          NaN          NaN   

             125          150          175          200  ...        425  \
0    183720.0000  195270.0000  206810.0000  218350.0000  ...        NaN   
1      2552.3000    2588.5000    2624.9000    2661.7000  ...        NaN   
2      2736.0000    2783.7000    2831.7000    2880.1000  ...        NaN   
3         9.6365       9.7527       9.8629       9.9679  ...        NaN   
4     18350.0000   19510.0000   20660.0000   21820.0000  ...        NaN   
..           ...          ...          ...          ...  ...        ...   
539          NaN          NaN          NaN          NaN  ...     6.2491   
540          NaN          NaN          NaN          NaN  ...    24.1040   
541          NaN          NaN          NaN          NaN  ...  2873.1000   
542          NaN          NaN          NaN          NaN  ...  3147.9000   
543          NaN          NaN          NaN          NaN  ...     6.2367   

             450        475          500        525          550        575  \
0    333730.0000        NaN  356810.0000        NaN  379880.0000        NaN   
1      3049.9000        NaN    3132.4000        NaN    3216.7000        NaN   
2      3383.6000        NaN    3489.2000        NaN    3596.5000        NaN   
3        10.8200        NaN      10.9612        NaN      11.0957        NaN   
4     33370.0000        NaN   35670.0000        NaN   37980.0000        NaN   
..           ...        ...          ...        ...          ...        ...   
539       6.3515     6.4452       6.5324     6.6147       6.6929     6.7679   
540      25.5990    27.0100      28.3590    29.6610      30.9250    32.1600   
541    2929.4000  2982.6000    3033.9000  3083.9000    3133.1000  3181.9000   
542    3221.2000  3290.5000    3357.2000  3422.1000    3485.7000  3548.5000   
543       6.3399     6.4341       6.5218     6.6043       6.6828     6.7580   

             600        625          650  
0    402960.0000        NaN  426040.0000  
1      3302.6000        NaN    3390.3000  
2      3705.6000        NaN    3816.4000  
3        11.2243        NaN      11.3476  
4     40290.0000        NaN   42600.0000  
..           ...        ...          ...  
539       6.8401     6.9099       6.9777  
540      33.3700    34.5600      35.7330  
541    3230.4000  3278.8000    3327.2000  
542    3610.8000  3672.8000    3734.6000  
543       6.8304     6.9004       6.9683  

[544 rows x 37 columns]

###Display the shape of data frame


In [ ]:
#your code here
print('Shape of data frame:', df.shape)

###Return an array containing names of all the columns

In [ ]:
#your code here
column_names = df.columns.to_numpy()
print("Names of all columns:", column_names)

###Display the number of null values in each column of the dataframe``



In [ ]:
#your code here
no_of_null_values = df.isnull().sum()
print("Number of null values in each column:")
print(no_of_null_values)

###Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
df['Property at Pressure']=df['Property'] + " at " + df['Pressure'].astype(str)
idx1=df[df['Property at Pressure']=='V at 10.0'].index
df['75'].loc[idx1].item()

16030.0

###Find out the column with the highest number of missing values

In [ ]:
#your code here
col_with_highest_missing_values = df.isnull().sum().idxmax()
print("Column with the highest number of missing values:", col_with_highest_missing_values)

###What is the average enthalpy of Sat. Liq. at all different pressures in the dataset ?

In [ ]:
print(df['Liq_Sat'].iloc[2::4].mean())

936.9707720588235


###Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here

#Section 3: PLotting the PLOTS

###Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
#your code here

###Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
#your code here

#Linear Regression
You're given a 100 data points generated from the function
$y=mx+c$. Some noise is added to the y values.

**Task:** Estimate the values of m and c using linear regression. Write a suitable cost function and update the parameters.

In [ ]:
 # Generation of data points
x = np.random.rand(100)*100
y = -4*x+15
y = y+np.random.randn(100)*30
plt.scatter(x,y)

In [ ]:
# Initialize parameters for the best-fit line y = mx + c
m0 = 1.0  # Initial value for slope
c0 = 0.0  # Initial value for y-intercept

print("Initial value for m:", m0)
print("Initial value for c:", c0)


# Cost function to be minimised
import numpy as np

# Linear regression model: y = mx + c
def linear_regression(m, x, c):
    return m*x + c

# Mean Squared Error cost function
def cost_function(y, m, x, c):
    pred = linear_regression(m, x, c)
    mse = np.mean((pred - y)**2)
    return mse

#Function for updating parameter


Run the model

In [ ]:
# define number of iterations for minimising cost function

# define the learning rate #

# run the model

In [ ]:
print(m,c)  # value should be close to (-4,15)